#!/bin/bash

echo "=== Golf App Network Setup Helper ==="
echo ""
echo "1. First, run 'ipconfig' in Windows Command Prompt to find your IPv4 address"
echo "   It should look like: 192.168.x.x"
echo ""
echo "2. Update mobile/src/config/api.js with your Windows IP address"
echo ""
echo "3. In Windows PowerShell (as Administrator), run:"
echo "   netsh interface portproxy add v4tov4 listenport=3000 listenaddress=0.0.0.0 connectport=3000 connectaddress=localhost"
echo ""
echo "4. Make sure Windows Firewall allows Node.js or port 3000"
echo ""
echo "5. Ensure your phone and computer are on the same Wi-Fi network"
echo ""
echo "Current backend status:"
curl -s http://localhost:3000/health && echo "✅ Backend is running locally" || echo "❌ Backend is not running"
echo ""
echo "To test from your phone:"
echo "1. Open browser on your phone"
echo "2. Navigate to: http://[YOUR-WINDOWS-IP]:3000/health"
echo "3. You should see a response if everything is working"